#!/bin/sh

set -eu

CONFFILE="/etc/keydb/keydb.conf"

if [ "${1}" = "purge" ]
then
	dpkg-statoverride --remove ${CONFFILE} || test $? -eq 2
fi

# Automatically added by dh_installinit/11.1.6ubuntu2
if [ "$1" = "purge" ] ; then
	update-rc.d keydb-server remove >/dev/null
fi


# In case this system is running systemd, we make systemd reload the unit files
# to pick up changes.
if [ -d /run/systemd/system ] ; then
	systemctl --system daemon-reload >/dev/null || true
fi
# End automatically added section
# Automatically added by dh_installdeb/11.1.6ubuntu2
dpkg-maintscript-helper rm_conffile /etc/keydb/keydb-server.pre-up.d/00_example 4:4.0.2-3~ -- "$@"
# End automatically added section
# Automatically added by dh_installdeb/11.1.6ubuntu2
dpkg-maintscript-helper rm_conffile /etc/keydb/keydb-server.pre-down.d/00_example 4:4.0.2-3~ -- "$@"
# End automatically added section
# Automatically added by dh_installdeb/11.1.6ubuntu2
dpkg-maintscript-helper rm_conffile /etc/keydb/keydb-server.post-up.d/00_example 4:4.0.2-3~ -- "$@"
# End automatically added section
# Automatically added by dh_installdeb/11.1.6ubuntu2
dpkg-maintscript-helper rm_conffile /etc/keydb/keydb-server.post-down.d/00_example 4:4.0.2-3~ -- "$@"
# End automatically added section


exit 0
