#!/bin/sh

set -eu

USER="keydb"
GROUP="$USER"
CONFFILE="/etc/keydb/keydb.conf"

if [ "$1" = "configure" ]
then
	if ! dpkg-statoverride --list ${CONFFILE} >/dev/null 2>&1
	then
		dpkg-statoverride --update --add ${USER} ${GROUP} 640 ${CONFFILE}
	fi
fi

# Automatically added by dh_installdeb/11.1.6ubuntu2
dpkg-maintscript-helper rm_conffile /etc/keydb/keydb-server.post-down.d/00_example 4:4.0.2-3~ -- "$@"
# End automatically added section
# Automatically added by dh_installdeb/11.1.6ubuntu2
dpkg-maintscript-helper rm_conffile /etc/keydb/keydb-server.post-up.d/00_example 4:4.0.2-3~ -- "$@"
# End automatically added section
# Automatically added by dh_installdeb/11.1.6ubuntu2
dpkg-maintscript-helper rm_conffile /etc/keydb/keydb-server.pre-down.d/00_example 4:4.0.2-3~ -- "$@"
# End automatically added section
# Automatically added by dh_installdeb/11.1.6ubuntu2
dpkg-maintscript-helper rm_conffile /etc/keydb/keydb-server.pre-up.d/00_example 4:4.0.2-3~ -- "$@"
# End automatically added section
# Automatically added by dh_installinit/11.1.6ubuntu2
if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-deconfigure" ] || [ "$1" = "abort-remove" ] ; then
	if [ -x "/etc/init.d/keydb-server" ]; then
		update-rc.d keydb-server defaults >/dev/null
		invoke-rc.d keydb-server start || exit 1
	fi
fi
# End automatically added section


if [ "$1" = "configure" ]
then
	find /etc/keydb -maxdepth 1 -type d -name 'keydb-server.*.d' -empty -delete
fi

exit 0
