#!/bin/sh
set -e
# Automatically added by dh_installinit/11.1.6ubuntu2
if [ -x "/etc/init.d/keydb-sentinel" ]; then
	invoke-rc.d keydb-sentinel stop || exit 1
fi
# End automatically added section
# Automatically added by dh_installdeb/11.1.6ubuntu2
dpkg-maintscript-helper rm_conffile /etc/keydb/keydb-sentinel.pre-up.d/00_example 4:4.0.2-3~ -- "$@"
# End automatically added section
# Automatically added by dh_installdeb/11.1.6ubuntu2
dpkg-maintscript-helper rm_conffile /etc/keydb/keydb-sentinel.pre-down.d/00_example 4:4.0.2-3~ -- "$@"
# End automatically added section
# Automatically added by dh_installdeb/11.1.6ubuntu2
dpkg-maintscript-helper rm_conffile /etc/keydb/keydb-sentinel.post-up.d/00_example 4:4.0.2-3~ -- "$@"
# End automatically added section
# Automatically added by dh_installdeb/11.1.6ubuntu2
dpkg-maintscript-helper rm_conffile /etc/keydb/keydb-sentinel.post-down.d/00_example 4:4.0.2-3~ -- "$@"
# End automatically added section
