#!/bin/sh
#
# Simple KeyDB init.d script conceived to work on Linux systems
# as it does use of the /proc filesystem.

### BEGIN INIT INFO
# Provides:     redis_6379
# Default-Start:        2 3 4 5
# Default-Stop:         0 1 6
# Short-Description:    KeyDB data structure server
# Description:          KeyDB data structure server. See https://keydb.dev
### END INIT INFO

KEYDBPORT=6379
EXEC=/usr/local/bin/keydb-server
CLIEXEC=/usr/local/bin/keydb-cli

PIDFILE=/var/run/redis_${KEYDBPORT}.pid
CONF="/etc/redis/${KEYDBPORT}.conf"

case "$1" in
    start)
        if [ -f $PIDFILE ]
        then
                echo "$PIDFILE exists, process is already running or crashed"
        else
                echo "Starting KeyDB server..."
                $EXEC $CONF
        fi
        ;;
    stop)
        if [ ! -f $PIDFILE ]
        then
                echo "$PIDFILE does not exist, process is not running"
        else
                PID=$(cat $PIDFILE)
                echo "Stopping ..."
                $CLIEXEC -p $KEYDBPORT shutdown
                while [ -x /proc/${PID} ]
                do
                    echo "Waiting for KeyDB to shutdown ..."
                    sleep 1
                done
                echo "KeyDB stopped"
        fi
        ;;
    *)
        echo "Please use start or stop as first argument"
        ;;
esac
