#!/bin/sh
set -e
# Automatically added by dh_installinit/11.1.6ubuntu1
if [ -x "/etc/init.d/keydb-sentinel" ]; then
        invoke-rc.d keydb-sentinel stop || exit 1
fi
# End automatically added section
# Automatically added by dh_installsystemd/11.1.6ubuntu1
if [ -d /run/systemd/system ] && [ "$1" = remove ]; then
        deb-systemd-invoke stop 'keydb-sentinel.service' >/dev/null || true
fi
# End automatically added section
